import type { TeamEnvironment, TeamflowConfig } from "../config/teamflowConfig.js";

/**
 * GitHub Actions templates derived from the team config. All pure string
 * builders so the exact YAML is unit-testable.
 *
 * CI auth uses the JWT bearer flow (headless, no interactive login). Each
 * environment expects three repo/environment secrets, suffixed by the
 * upper-cased environment name:
 *   SF_<ENV>_CLIENT_ID    — connected app consumer key
 *   SF_<ENV>_USERNAME     — integration user username
 *   SF_<ENV>_JWT_KEY      — PEM private key (the whole key, as a secret)
 * and one variable SF_<ENV>_INSTANCE_URL (login URL).
 */

export function secretPrefix(env: TeamEnvironment): string {
  return `SF_${env.name.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}`;
}

/** A GH Actions `if:` expression matching this environment's branch. */
export function branchCondition(env: TeamEnvironment): string {
  if (env.branch.includes("*")) {
    const prefix = env.branch.slice(0, env.branch.indexOf("*"));
    return `startsWith(github.ref, 'refs/heads/${prefix}')`;
  }
  return `github.ref == 'refs/heads/${env.branch}'`;
}

/** Branch names (literal or glob) used for workflow `on:` push/PR filters. */
export function branchFilters(config: TeamflowConfig): string[] {
  return [...new Set(config.environments.map((e) => e.branch))];
}

const SETUP_STEPS = (packageDirs: string[]): string => `      - name: Checkout (full history for diff)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli@latest

      - name: Show package directories
        run: echo "Deploying from: ${packageDirs.join(", ")}"`;

function authStep(env: TeamEnvironment): string {
  const p = secretPrefix(env);
  return `      - name: Authenticate to ${env.name} (JWT)
        run: |
          echo "\${{ secrets.${p}_JWT_KEY }}" > /tmp/server.key
          sf org login jwt \\
            --client-id "\${{ secrets.${p}_CLIENT_ID }}" \\
            --jwt-key-file /tmp/server.key \\
            --username "\${{ secrets.${p}_USERNAME }}" \\
            --instance-url "\${{ vars.${p}_INSTANCE_URL || 'https://login.salesforce.com' }}" \\
            --alias ${env.orgAlias} \\
            --set-default`;
}

/** PR validation: check-only deploy of the diff vs the PR base branch. */
export function prValidationWorkflow(config: TeamflowConfig): string {
  const dirs = config.packageDirectories;
  const filters = branchFilters(config)
    .map((b) => `      - "${b}"`)
    .join("\n");
  // Use the first environment whose branch matches the PR base; fall back to
  // the production env's policy for the validation test level.
  const envCases = config.environments
    .map(
      (env) => `          if [ "$BASE" = "${env.branch}" ] || [[ "${env.branch}" == *"*"* && "$BASE" == ${env.branch} ]]; then
            ALIAS="${env.orgAlias}"; LEVEL="${env.testLevel || config.testLevel}"
          fi`
    )
    .join("\n");
  const authSteps = config.environments.map(authStep).join("\n\n");

  return `# Generated by Salesforce Dev Manager — PR validation (check-only deploy + tests)
name: SF Validate (PR)

on:
  pull_request:
    branches:
${filters}
    paths:
${dirs.map((d) => `      - "${d}/**"`).join("\n")}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
${SETUP_STEPS(dirs)}

${authSteps}

      - name: Compute changed metadata vs base
        id: diff
        run: |
          BASE="\${{ github.base_ref }}"
          git fetch origin "$BASE" --depth=0 || true
          CHANGED=$(git diff --name-only "origin/$BASE...HEAD" -- ${dirs.join(" ")} | tr '\\n' ' ')
          echo "Changed: $CHANGED"
          echo "files=$CHANGED" >> "$GITHUB_OUTPUT"

      - name: Resolve target org + test level
        id: target
        run: |
          BASE="\${{ github.base_ref }}"
          ALIAS=""; LEVEL="${config.testLevel}"
${envCases}
          echo "alias=$ALIAS" >> "$GITHUB_OUTPUT"
          echo "level=$LEVEL" >> "$GITHUB_OUTPUT"

      - name: Validate (check-only) deploy
        if: steps.diff.outputs.files != ''
        run: |
          DIRS=""
          for f in \${{ steps.diff.outputs.files }}; do DIRS="$DIRS -d $f"; done
          sf project deploy validate $DIRS \\
            --target-org "\${{ steps.target.outputs.alias }}" \\
            --test-level "\${{ steps.target.outputs.level }}"

      - name: No metadata changed
        if: steps.diff.outputs.files == ''
        run: echo "No package metadata changed — skipping validation."
`;
}

/** Deploy on push/merge to an environment branch. One job per environment. */
export function deployWorkflow(config: TeamflowConfig): string {
  const dirs = config.packageDirectories;
  const filters = branchFilters(config)
    .map((b) => `      - "${b}"`)
    .join("\n");

  const jobs = config.environments
    .map((env) => {
      const level = env.testLevel || config.testLevel;
      return `  deploy-${env.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}:
    name: Deploy → ${env.name} (${env.orgAlias})
    if: ${branchCondition(env)}
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${env.name}
      cancel-in-progress: false
    steps:
${SETUP_STEPS(dirs)}

${authStep(env)}

      - name: Compute changed metadata since last deploy
        id: diff
        run: |
          BEFORE="\${{ github.event.before }}"
          if [ -z "$BEFORE" ] || ! git cat-file -e "$BEFORE^{commit}" 2>/dev/null; then
            BEFORE=$(git rev-parse HEAD~1 2>/dev/null || git rev-parse HEAD)
          fi
          CHANGED=$(git diff --name-only "$BEFORE" HEAD -- ${dirs.join(" ")} | tr '\\n' ' ')
          echo "Changed: $CHANGED"
          echo "files=$CHANGED" >> "$GITHUB_OUTPUT"

      - name: Deploy diff to ${env.name}
        if: steps.diff.outputs.files != ''
        run: |
          DIRS=""
          for f in \${{ steps.diff.outputs.files }}; do DIRS="$DIRS -d $f"; done
          sf project deploy start $DIRS \\
            --target-org ${env.orgAlias} \\
            --test-level ${level} \\
            --wait 60

      - name: Nothing to deploy
        if: steps.diff.outputs.files == ''
        run: echo "No package metadata changed since last deploy."`;
    })
    .join("\n\n");

  return `# Generated by Salesforce Dev Manager — deploy on merge to environment branches
name: SF Deploy

on:
  push:
    branches:
${filters}
    paths:
${dirs.map((d) => `      - "${d}/**"`).join("\n")}

jobs:
${jobs}
`;
}

/** A starter CODEOWNERS pointing the team at the package dirs + CI config. */
export function codeowners(config: TeamflowConfig): string {
  return `# Generated by Salesforce Dev Manager — assign reviewers per area.
# Replace @your-team / @your-org with real GitHub teams or users.

* @your-team

${config.packageDirectories.map((d) => `${d}/ @your-team`).join("\n")}

sf-teamflow.json @your-team-leads
.github/ @your-team-leads
`;
}

export interface ScaffoldFile {
  /** Path relative to the workspace root. */
  relativePath: string;
  content: string;
}

/** All files the CI/CD scaffolder writes for a given config. */
export function cicdFiles(config: TeamflowConfig): ScaffoldFile[] {
  return [
    { relativePath: ".github/workflows/sf-validate.yml", content: prValidationWorkflow(config) },
    { relativePath: ".github/workflows/sf-deploy.yml", content: deployWorkflow(config) },
    { relativePath: ".github/CODEOWNERS", content: codeowners(config) },
  ];
}
