import type { TeamEnvironment, TeamflowConfig } from "../config/teamflowConfig.js";
import { testLevelFor } from "../config/teamflowConfig.js";

/**
 * GitHub Actions templates derived from the team config. All pure string
 * builders so the exact YAML is unit-testable.
 *
 * CI auth uses the JWT bearer flow (headless, no interactive login). Each
 * environment expects three repo/environment secrets, suffixed by the
 * upper-cased environment name:
 *   SF_<ENV>_CLIENT_ID    — connected app consumer key
 *   SF_<ENV>_USERNAME     — integration user username
 *   SF_<ENV>_JWT_KEY      — PEM private key (the whole key, as a secret)
 * and one variable SF_<ENV>_INSTANCE_URL (login URL).
 */

/**
 * ASCII-safe, environment-unique slug for job ids / secret names. Uses the
 * environment name; but if the name has no ASCII (e.g. 日本語のみ「開発環境」),
 * every env would collapse to the same slug and produce duplicate job ids /
 * colliding secrets — so it falls back to the unique `orgAlias`. Pure & tested.
 */
export function envSlug(env: TeamEnvironment): string {
  const nameSlug = env.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  if (/[a-z0-9]/.test(env.name.toLowerCase())) {
    return nameSlug;
  }
  const aliasSlug = (env.orgAlias || "").toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return aliasSlug || "env";
}

export function secretPrefix(env: TeamEnvironment): string {
  return `SF_${envSlug(env).toUpperCase().replace(/-/g, "_")}`;
}

/**
 * 複数環境が同じ envSlug に collapse して衝突するかを検出する。
 * envSlug は deploy の job id とシークレット接頭辞(secretPrefix)の両方の根なので、
 * 衝突すると「YAMLの重複ジョブID」「同名シークレットの上書き」でCIが壊れる。
 * 例: "UAT EU" と "UAT-EU" はどちらも slug "uat-eu" → SF_UAT_EU。
 * 衝突した slug ごとに影響環境名の配列を返す（衝突なしなら空配列）。Pure & unit-tested.
 */
export function envSlugCollisions(config: TeamflowConfig): { slug: string; envs: string[] }[] {
  const bySlug = new Map<string, string[]>();
  for (const env of config.environments) {
    const slug = envSlug(env);
    const list = bySlug.get(slug) ?? [];
    list.push(env.name);
    bySlug.set(slug, list);
  }
  return [...bySlug.entries()]
    .filter(([, envs]) => envs.length > 1)
    .map(([slug, envs]) => ({ slug, envs }));
}

/** A GH Actions `if:` expression matching this environment's branch. */
export function branchCondition(env: TeamEnvironment): string {
  if (env.branch.includes("*")) {
    const prefix = env.branch.slice(0, env.branch.indexOf("*"));
    return `startsWith(github.ref, 'refs/heads/${prefix}')`;
  }
  return `github.ref == 'refs/heads/${env.branch}'`;
}

/** Branch names (literal or glob) used for workflow `on:` push/PR filters. */
export function branchFilters(config: TeamflowConfig): string[] {
  return [...new Set(config.environments.map((e) => e.branch))];
}

const SETUP_STEPS = (packageDirs: string[]): string => `      - name: Checkout (full history for diff)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli@latest

      - name: Show package directories
        run: echo "Deploying from: ${packageDirs.join(", ")}"`;

function authStep(env: TeamEnvironment): string {
  const p = secretPrefix(env);
  return `      - name: Authenticate to ${env.name} (JWT)
        run: |
          echo "\${{ secrets.${p}_JWT_KEY }}" > /tmp/server.key
          sf org login jwt \\
            --client-id "\${{ secrets.${p}_CLIENT_ID }}" \\
            --jwt-key-file /tmp/server.key \\
            --username "\${{ secrets.${p}_USERNAME }}" \\
            --instance-url "\${{ vars.${p}_INSTANCE_URL || 'https://login.salesforce.com' }}" \\
            --alias ${env.orgAlias} \\
            --set-default`;
}

/** PR validation: check-only deploy of the diff vs the PR base branch. */
export function prValidationWorkflow(config: TeamflowConfig): string {
  const dirs = config.packageDirectories;
  const filters = branchFilters(config)
    .map((b) => `      - "${b}"`)
    .join("\n");
  // Use the first environment whose branch matches the PR base; fall back to
  // the production env's policy for the validation test level.
  const envCases = config.environments
    .map(
      (env) => `          if [ "$BASE" = "${env.branch}" ] || [[ "${env.branch}" == *"*"* && "$BASE" == ${env.branch} ]]; then
            ALIAS="${env.orgAlias}"; LEVEL="${testLevelFor(config, env)}"
          fi`
    )
    .join("\n");
  const authSteps = config.environments.map(authStep).join("\n\n");

  return `# Generated by Salesforce Dev Manager — PR validation (check-only deploy + tests)
name: SF Validate (PR)

on:
  pull_request:
    branches:
${filters}
    paths:
${dirs.map((d) => `      - "${d}/**"`).join("\n")}

# GITHUB_TOKEN は最小権限に。リポジトリ読み取りのみ許可（デプロイは secrets 経由で外部Orgへ）。
permissions:
  contents: read

# 同じPRに新しいコミットが来たら、進行中の古い検証はキャンセルしてCI時間を節約。
concurrency:
  group: sf-validate-\${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
${SETUP_STEPS(dirs)}

${authSteps}

      - name: Compute changed metadata vs base
        id: diff
        run: |
          BASE="\${{ github.base_ref }}"
          # baseブランチを取得（checkoutは fetch-depth:0 なので merge-base に十分な履歴が得られる）。
          # 注: depth 指定は付けない（git の depth は正の整数のみで 0 は不正）。
          git fetch origin "$BASE" || true
          CHANGED=$(git diff --name-only "origin/$BASE...HEAD" -- ${dirs.join(" ")} | tr '\\n' ' ')
          echo "Changed: $CHANGED"
          echo "files=$CHANGED" >> "$GITHUB_OUTPUT"

      - name: Resolve target org + test level
        id: target
        run: |
          BASE="\${{ github.base_ref }}"
          ALIAS=""; LEVEL="${config.testLevel}"
${envCases}
          echo "alias=$ALIAS" >> "$GITHUB_OUTPUT"
          echo "level=$LEVEL" >> "$GITHUB_OUTPUT"

      - name: Validate (check-only) deploy
        if: steps.diff.outputs.files != ''
        run: |
          DIRS=""
          for f in \${{ steps.diff.outputs.files }}; do DIRS="$DIRS -d $f"; done
          sf project deploy validate $DIRS \\
            --target-org "\${{ steps.target.outputs.alias }}" \\
            --test-level "\${{ steps.target.outputs.level }}"

      - name: No metadata changed
        if: steps.diff.outputs.files == ''
        run: echo "No package metadata changed — skipping validation."

  apex-pmd:
    name: Apex 静的解析 (PMD)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Salesforce CLI + Code Analyzer を準備
        run: |
          npm install --global @salesforce/cli@latest
          sf plugins install @salesforce/sfdx-scanner@latest
      - name: PMD で Apex / メタデータを静的解析
        run: |
          sf scanner run \\
            --target "${dirs.join(",")}" \\
            --engine pmd \\
            --format table
          # ↑問題があってもPRは止めません（レポートのみ）。
          # 一定以上の重大度で失敗させたい場合は次の行を上の run に追加:
          #   --severity-threshold 2

  lwc-jest:
    name: LWC 単体テスト (Jest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: LWC があれば Jest を実行
        run: |
          if find ${dirs.join(" ")} -type d -name lwc 2>/dev/null | grep -q .; then
            npm ci || npm install
            npm run test:unit --if-present || npx --yes @salesforce/sfdx-lwc-jest --skip-api-version-check
          else
            echo "LWC コンポーネントが無いためスキップします。"
          fi

  format-check:
    name: コード整形チェック (Prettier)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Prettier 設定があれば整形をチェック（レポートのみ）
        run: |
          if [ -f .prettierrc ] || [ -f .prettierrc.json ] || [ -f .prettierrc.yaml ] || [ -f .prettierrc.js ] || [ -f prettier.config.js ] || grep -q '"prettier"' package.json 2>/dev/null; then
            npm ci || npm install
            npx --yes prettier --check "${dirs.map((d) => `${d}/**/*.{cls,trigger,js,html,xml}`).join("\" \"")}" \\
              || echo "::warning::整形されていないファイルがあります（ローカルで npx prettier --write で整えられます）。"
          else
            echo "Prettier 設定が無いためスキップします。"
          fi

  lint-lwc:
    name: コード品質チェック (ESLint・LWC/Aura)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: ESLint 設定とLWCがあれば実行（レポートのみ）
        run: |
          if find ${dirs.join(" ")} -type d \\( -name lwc -o -name aura \\) 2>/dev/null | grep -q . \\
            && { [ -f .eslintrc.json ] || [ -f .eslintrc.js ] || [ -f .eslintrc ] || [ -f eslint.config.js ] || grep -q '"eslintConfig"' package.json 2>/dev/null; }; then
            npm ci || npm install
            npm run lint --if-present \\
              || echo "::warning::ESLintの指摘があります（npm run lint で確認できます）。"
          else
            echo "ESLint 設定 または LWC/Aura が無いためスキップします。"
          fi
`;
}

/** Deploy on push/merge to an environment branch. One job per environment. */
export function deployWorkflow(config: TeamflowConfig): string {
  const dirs = config.packageDirectories;
  const filters = branchFilters(config)
    .map((b) => `      - "${b}"`)
    .join("\n");

  const jobs = config.environments
    .map((env) => {
      const level = testLevelFor(config, env);
      return `  deploy-${envSlug(env)}:
    name: Deploy → ${env.name} (${env.orgAlias})
    if: ${branchCondition(env)}
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${envSlug(env)}
      cancel-in-progress: false
    steps:
${SETUP_STEPS(dirs)}

${authStep(env)}

      - name: Compute changed metadata since last deploy
        id: diff
        run: |
          BEFORE="\${{ github.event.before }}"
          ZERO="0000000000000000000000000000000000000000"
          if [ -z "$BEFORE" ] || [ "$BEFORE" = "$ZERO" ] || ! git cat-file -e "$BEFORE^{commit}" 2>/dev/null; then
            BEFORE=$(git rev-parse HEAD~1 2>/dev/null || echo "")
          fi
          if [ -n "$BEFORE" ]; then
            CHANGED=$(git diff --name-only "$BEFORE" HEAD -- ${dirs.join(" ")} | tr '\\n' ' ')
          else
            # 初回(親コミット無し): パッケージ全体をデプロイ（取りこぼし防止）。
            CHANGED="${dirs.join(" ")}"
          fi
          echo "Changed: $CHANGED"
          echo "files=$CHANGED" >> "$GITHUB_OUTPUT"

      - name: Deploy diff to ${env.name}
        if: steps.diff.outputs.files != ''
        run: |
          DIRS=""
          for f in \${{ steps.diff.outputs.files }}; do DIRS="$DIRS -d $f"; done
          sf project deploy start $DIRS \\
            --target-org ${env.orgAlias} \\
            --test-level ${level} \\
            --wait 60

      - name: Nothing to deploy
        if: steps.diff.outputs.files == ''
        run: echo "No package metadata changed since last deploy."`;
    })
    .join("\n\n");

  return `# Generated by Salesforce Dev Manager — deploy on merge to environment branches
name: SF Deploy

on:
  push:
    branches:
${filters}
    paths:
${dirs.map((d) => `      - "${d}/**"`).join("\n")}

# GITHUB_TOKEN は最小権限に。リポジトリ読み取りのみ許可（デプロイは secrets 経由で外部Orgへ）。
permissions:
  contents: read

jobs:
${jobs}
`;
}

/** A starter CODEOWNERS pointing the team at the package dirs + CI config. */
export function codeowners(config: TeamflowConfig): string {
  return `# Generated by Salesforce Dev Manager — assign reviewers per area.
# 下の例の行頭 # を外し、@your-team を実在の GitHub チーム(@org/team)やユーザー(@user)に
# 置き換えてください。置き換えるまではコメントのままにしておくと、GitHub の
# 「unknown owner @your-team」エラーを避けられます（無効＝レビュアー自動指定なし）。

# * @your-team

${config.packageDirectories.map((d) => `# ${d}/ @your-team`).join("\n")}

# sf-teamflow.json @your-team-leads
# .github/ @your-team-leads
`;
}

export interface ScaffoldFile {
  /** Path relative to the workspace root. */
  relativePath: string;
  content: string;
}

/** All files the CI/CD scaffolder writes for a given config. */
export function cicdFiles(config: TeamflowConfig): ScaffoldFile[] {
  return [
    { relativePath: ".github/workflows/sf-validate.yml", content: prValidationWorkflow(config) },
    { relativePath: ".github/workflows/sf-deploy.yml", content: deployWorkflow(config) },
    { relativePath: ".github/CODEOWNERS", content: codeowners(config) },
  ];
}
